### ISSUE TITLE
Accepting pull requests

### ISSUE THREAD

**Issue by fozy81** [koki25ando/FlickrAPI#1]
I made some changes to flcikrapi - are you accepting contributions/pull requests?

**Comment by fozy81** [comment]
Its adds function for searching, for example: photo_search <- function(api_key, tags, page=1, per_page = 500).

**Comment by koki25ando** [comment]
thank you for your contribution, and apologies for the lack of a reply for so long.
I am interested in your ideas, could you please share your codes?

**Comment by fozy81** [comment]
Sorry, for slow response. I'll try to dig out the code...

**Comment by fozy81** [comment]
Hi @koki25ando, please see PR.

**Comment by koki25ando** [comment]
@fozy81 thanks for sharing your code! i will check it out and will give you updates soon.

**Comment by fozy81** [comment]
@koki25ando  Thanks for reviewing my PR request :smile:  :champagne:  - happy to contribute.
