### ISSUE TITLE
Broken pkgdown website after recent pull request

### ISSUE THREAD

**Issue by elipousson** [koki25ando/FlickrAPI#13]
Hello @koki25ando! Sorry to say that it looks like my recent pull request broke the pkgdown website. I'm hoping it may just be a issue with the settings for GitHub Pages but I'm not 100% sure. Can you double-check the GitHub pages settings to see if that is the issue?

Also – I didn't mean to create a bunch of extra chores for you. No pressure but if it helps to add me as a collaborator to the repo, I'd be happy to work make commits and merge pull requests to get the package ready to resubmit to CRAN.

**Comment by koki25ando** [comment]
@elipousson hello!! 
thanks for spotting issues. I will check GitHub pages setting, and see if it is the issue.

And, i have just added you as collaborator to this repo. please check your status and feel free to make commits.
also I think the idea to resubmit this package as new version to CRAN is good. I'm happy to help you any time so please let me know if you have any questions.

**Comment by elipousson** [comment]
Great. Thanks for giving me contributor access! I just made a couple updates to the pkgdown site that I thought might have been causing the problem but it doesn't look like it solved the issue.

When you look at the GitHub pages settings, does it look something like this (but with master instead of main for the branch)? 

<img width="714" alt="Screen Shot 2022-03-04 at 9 21 13 AM" src="https://user-images.githubusercontent.com/931136/156780236-b6c0a6f5-4a0d-42f1-8f43-9a8fdc4aa5d0.png">

**Comment by koki25ando** [comment]
@elipousson I just checked GitHub pages setting and it looks exactly like you describe.

If you don't mind, could you give me some instructions of what should be done to resolve issues...

**Comment by elipousson** [comment]
I'm honestly not sure since the website seems like it built fine on my end when I updated it. I'll do some investigation this weekend and see if I can figure it out.

**Comment by elipousson** [comment]
Got it! The .gitignore was keeping several dependencies from being added to the docs folder https://github.com/koki25ando/FlickrAPI/commit/b81b1e7cc05ed0c94e01e60de4b82e29b84d5415
