### ISSUE TITLE
Resubmitting FlickrAPI to CRAN

### ISSUE THREAD

**Issue by elipousson** [koki25ando/FlickrAPI#15]
Hello @koki25ando – I didn't realize that [FlickrAPI was taken down from CRAN](https://cran-archive.r-project.org/web/checks/2022/2022-05-09_check_results_FlickrAPI.html) back in May due to three notes. Frustrating that it doesn't even take warnings or errors to get a package taken down! Regardless, I'm assuming you either didn't see the alerts or didn't have time to address them before CRAN removed the package.

I'm unfamiliar with the process but would you be interested in adding my email to the list of maintainers on CRAN so I can get alerts in the future? If so, could you set that up sometime in the next couple weeks?

If not, I think the package should pass re-submission to CRAN already but it may be a good idea to bump the version number to reflect the fixes and the recently added functionality.

**Comment by koki25ando** [comment]
@elipousson 
Thanks for letting me know. As you have written, I didn't realize the alerts from CRAN.
I will try to resubmit this week, and make sure your email will be included as a maintainer. also will include recent versions.

**Comment by koki25ando** [comment]
@elipousson i wasn't aware before i checked directory, 
resubmission was approved!! and is now available on CRAN!!
https://cran.r-project.org/web/packages/FlickrAPI/index.html

**Comment by elipousson** [comment]
Awesome! That is great to hear.
